### PR TITLE
fix(Checkbox)!: adding emphasis styles, moving notes to below label

### PR DESCRIPTION
**Pull request by dominiquemb**

### CODE REVIEW

**Comment by SamuelAlev** [comment]
Renaming/deleting props is a breaking change and breaking changes needs a `!`

**Review by imoutaharik — COMMENTED** [review]
Screenshot 2023-02-08 at 16 35 31

I believe that according to Figma, the background colour for the checkbox should be base and change to box-neutral on hover.

**Comment by dominiquemb** [comment]
> Screenshot 2023-02-08 at 16 35 31
> 
> I believe that according to Figma, the background colour for the checkbox should be base and change to box-neutral on hover.

Good catch. Fixed!

**Review by imoutaharik — APPROVED** [review]
Once this gets released, It would be nice to quickly fix the types in Clarify. 
`/client/Common/Form/Checkbox`

**Pull request merged**
