### PR TITLE
fix: due to accessibility issues, an additional input type has been added.

### PR DESCRIPTION
**Pull request by bojangles-m**

### CODE REVIEW

**Review by noahwaldner — APPROVED** [review]

**Comment by noahwaldner** [comment]
Good Change 👍🏻 LGTM ✨

**Comment by bojangles-m** [comment]
@noahwaldner why cant this be merged to main?

**Comment by SamuelAlev** [comment]
You could merge it, I don't see any blocking checks 🤔

**Comment by bojangles-m** [comment]
> You could merge it, I don't see any blocking checks 🤔
There were no blocking checked but i could not merge it and I dont know why?

**Pull request merged**
