### PR TITLE
refactor(Checklist): span last element in multiple columns mode

### PR DESCRIPTION
**Pull request by fabriciomendonca**

### CODE REVIEW

**Comment by imoutaharik** [comment]
@fabriciomendonca There are 2 new code smells introduced in that PR. Would be nice to fix. thanks.

**Comment by fabriciomendonca** [comment]
> @fabriciomendonca There are 2 new code smells introduced in that PR. Would be nice to fix. thanks.

Fixed the code smells, @imoutaharik

**Comment by imoutaharik** [comment]
@fabriciomendonca On the last 2 stories for the checklist, we lost the interaction on the checkboxes, it would be nice to add it.

**Comment by fabriciomendonca** [comment]
> @fabriciomendonca On the last 2 stories for the checklist, we lost the interaction on the checkboxes, it would be nice to add it.

Nice catch. I forgot to use the new component I created for those stories to avoiding code duplication: `MultipleColumnsComponent`

**Review by imoutaharik — APPROVED** [review]

**Pull request merged**
