### PR TITLE
feat: passed callback prop

### PR DESCRIPTION
**Pull request by bojangles-m**
If the component using modal needs to execute sam function at the closing event then this is the callback that can be triggered at closing modal.

I used effect instead of this and it was triggered twice if we use callback is triggered once.

And also removed the function on the 30 line because it is not needed the setAction can be passed directly.

### CODE REVIEW

**Comment by ryancarville** [comment]
Hey @bojangles-m.  I test this locally and it looks like it is effecting the `Dialog` positioning.  Also not sure if this is the reason, but the `Modal` and `Dropdown` (both use `useOverlay`) are also not rendering as they should in Storybook. 

Screenshot 2023-10-27 at 09 28 13
Screenshot 2023-10-27 at 09 29 13
Screenshot 2023-10-27 at 09 29 55

**Comment by bojangles-m** [comment]
I guess only the last beta in this PR was missing.

**Comment by bojangles-m** [comment]
@ryancarville could you please confirm that?

**Review by ryancarville — APPROVED** [review]
👍

**Pull request merged**
