### PR TITLE
refactor(overlays)!: Simplify usage introducing anchor property and new Design

### PR DESCRIPTION
**Pull request by imoutaharik**
## Definition of Done
- [x] User interface and experience have been verified by a designer
- [x] I have added thorough Cypress tests (All properties and interactions have been tested).
- [x] Cross-browser compatibility - The component look consistent in the latest version of Chrome, Safari, Firefox and Edge.
- [x] I've added documentation in Storybook. all properties are reflected in table and controls.
- [x] User interface is compliant with WCAG 2.1 AA. Ensure these items are fulfilled:
    - [x] Keyboard operability: All functionality can be accessed using only the keyboard
    - [x] Logical tab order: Interactive elements follow a consistent and logical tab order
    - [x] Visual indication of focus: Focused elements are visually highlighted for keyboard navigation
    - [x] Color contrast: Sufficient contrast is used between text and background, as well as form fields and background
    - [x] Alternative visual cues: Information is not solely reliant on color and includes alternative visual indicators
    - [x] Semantic markup: Headings, lists, and form elements are marked up with appropriate semantic tags
    
    
    As This PR is already quite big, the following tasks will be tackled in another PR:
    - SideContentImage on Dialog component
    - Add EnterDelay and LeaveDelay on Popover
    - More in context Stories and tests for accessibility.

### CODE REVIEW

**Review by ryancarville — COMMENTED** [review]
Not sure if this is intentional, but when the `Dialog` is `open` it opens to what ever the last state it was in. 

E.g if there is a `Select` menu as a `child` of the `Dialog`. On initial open it is closed ~> then the `Select` is opened ~> then the `Dialog` is closed while the `Select` is open ~> when the `Dialog` is re-opened the `Select` menu is open.

**Review by anxobotana — APPROVED** [review]
Tree related file looks good and works as expected

**Comment by imoutaharik** [comment]
> Not sure if this is intentional, but when the `Dialog` is `open` it opens to what ever the last state it was in.
> 
> E.g if there is a `Select` menu as a `child` of the `Dialog`. On initial open it is closed ~> then the `Select` is opened ~> then the `Dialog` is closed while the `Select` is open ~> when the `Dialog` is re-opened the `Select` menu is open.

Updated @ryancarville

**Review by ryancarville — APPROVED** [review]
LGTM 👍

**Pull request merged**
