### PR TITLE
fix(Accordion): update focus styling to include header

### PR DESCRIPTION
**Pull request by ryancarville**
Update to the `FOCUS_STYLE` properties on the `Accordion` to wrap all elements and not just collapsible content.  

Secondly, because the neighbouring `div` has a `button` child, the focused element needs to be set to `position: relative` to allow for the z-index to take priority and not be overlapped.

Bug Report: https://frontify.slack.com/archives/C02PSJTPA3D/p1689079198399909

ClickUp: https://app.clickup.com/t/862k4a2gm

### CODE REVIEW

**Comment by bojangles-m** [comment]
First child
Screenshot 2023-10-18 at 10 27 04

Second child
Screenshot 2023-10-18 at 10 27 13

And then I found also this one!
Screenshot 2023-10-18 at 10 28 15

**Review by bojangles-m — CHANGES_REQUESTED** [review]
Great take, I just found some inconsistency

**Comment by ryancarville** [comment]
> Great take, I just found some inconsistency

I don't understand.  Could you elaborate on the inconsistencies?

**Comment by bojangles-m** [comment]
> > Great take, I just found some inconsistency
> 
> I don't understand. Could you elaborate on the inconsistencies? For the last one, is it the overlap on the `switch`? If so this is a separate issue, but can be addressed by adding a larger default top `margin` on the `Collapsible` child.

yes it is the overlap. Ok if that is already known you can just ignore it.

**Comment by bojangles-m** [comment]
The other thing is inconsistency with the frame around first child and other children if you look in the picture?

**Comment by ryancarville** [comment]
We can add a minimal `marginTop` to the child to get it a little more space. Not a bad idea in general.  As for the `focusRing` it is a difficult one as there is a `2px` offset which overlaps the neighbours.  Checking with the designer to see if there are objections to using a ring with no offset.

**Comment by ryancarville** [comment]
@bojangles-m added a no offset focus styling variant and margin top to content child.

**Comment by bojangles-m** [comment]
> @bojangles-m added a no offset focus styling variant and margin top to content child.

If we do it like that and then the style compared to other components is not consistant?

**Comment by ryancarville** [comment]
No really as the  `Accordion` has no border.  Only the "divider".  So technically it is not included in with the element.

**Comment by bojangles-m** [comment]
Great job thnx

**Review by bojangles-m — APPROVED** [review]

**Pull request merged**
