### PR TITLE
fix(Icon)!: remove Size8

### PR DESCRIPTION
**Pull request by jonasbuechel**
### Why I like to remove it
There are no SVGs with size 8 available. By using IconSize.Size8 no Icon is shown. The only use case is within a badge test case. Badges defines the size of its icons, so this test case does not reflect how it works.

### How to demonstrate Icons are not working with Size8
Replace `export const Icon....` in Icon.stories.tsx with:
```
export const Icon: StoryFn<IconProps> = (args: IconProps) => (
    <ul className="tw-grid tw-grid-cols-4 tw-gap-4">
        <IconComponent icon={IconEnum.Johanna} size={IconSize.Size8} />
        <IconComponent icon={IconEnum.Johanna} size={IconSize.Size12} />
        <IconComponent icon={IconEnum.Johanna} size={IconSize.Size16} />
        <IconComponent icon={IconEnum.Johanna} size={IconSize.Size20} />
        <IconComponent icon={IconEnum.Johanna} size={IconSize.Size24} />
        <IconComponent icon={IconEnum.Johanna} size={IconSize.Size32} />
    </ul>
);
```

### How to retest badges with overwriting icons size
Add this story to Badge.stories.tsx to take a look:
```
export const BadgeTest: StoryFn<BadgeProps> = () => (
    <div>
        <Badge icon={<IconDocumentText size={IconSize.Size8} />}>MY BADGE</Badge>
        <Badge icon={<IconDocumentText size={IconSize.Size12} />}>MY BADGE</Badge>
        <Badge icon={<IconDocumentText size={IconSize.Size16} />}>MY BADGE</Badge>
        <Badge icon={<IconDocumentText size={IconSize.Size20} />}>MY BADGE</Badge>
        <Badge icon={<IconDocumentText size={IconSize.Size24} />}>MY BADGE</Badge>
        <Badge icon={<IconDocumentText size={IconSize.Size32} />}>MY BADGE</Badge>
        <Badge icon={<IconDocumentText size={IconSize.Size32} />}>MY BADGE</Badge>
    </div>
);
```

### CODE REVIEW

**Comment by thisguyscode** [comment]
@jonasbuechel - I think the intention was that `Size8` scales down the `Size12`. If that's not the case then perhaps we can remove (for now), but otherwise are you sure that this is not used outside of Fondue (consuming applications)?

**Comment by imoutaharik** [comment]
> @jonasbuechel - I think the intention was that `Size8` scales down the `Size12`. If that's not the case then perhaps we can remove (for now), but otherwise are you sure that this is not used outside of Fondue (consuming applications)?

@thisguyscode I don't think this is used outside because it doesn't work. If you use size8, no icons is showing.

**Review by imoutaharik — COMMENTED** [review]
It looks good to me 👍🏼 , I'm in favor to remove it. There is just that tiny typecheck, the IconSize is still declared in the test file. 😉

**Comment by jonasbuechel** [comment]
> It looks good to me 👍🏼 , I'm in favor to remove it. There is just that tiny typecheck, the IconSize is still declared in the test file. 😉

Solved 👌 

I had a chat with @celine-s, Size8 is not used in the blocks and I removed the last usage within Clarify 👍

**Review by imoutaharik — APPROVED** [review]

**Pull request merged**
